title_name = "Grand Theft Auto V" # Five
title_id = "545408A7" # TT-2215
hash = "8CB3745EED1C5043" # default.xex
#media_id = "79E465C5"

[[patch]]
    name = "Fix Beta Crash"
    desc = "This patch is a workaround for the protect_zero requirment. This patch will also get beta working on console, you may need to uninstall unsupported DLCs."
    author = "Adrian, Byrom"
    is_enabled = false

    [[patch.be32]]
        address = 0x82cf363c
        value = 0x38600000

    [[patch.be32]]
        address = 0x826db920
        value = 0x38600000

    [[patch.be32]]
        address = 0x8345b930
        value = 0x60000000

    [[patch.be32]]
        address = 0x8246380c
        value = 0x60000000
